/**
 * Client experiences, shared anonymously. Wording is the clients' own; names
 * and identifying details are withheld to protect confidentiality.
 */

export type Topic = "everyday" | "students" | "relationships" | "transitions" | "confidence" | "parents" | "experience";

export const topics: { id: Topic; label: string }[] = [
  { id: "everyday", label: "Stress & everyday pressure" },
  { id: "students", label: "Students & young adults" },
  { id: "relationships", label: "Relationships & boundaries" },
  { id: "transitions", label: "Family & life transitions" },
  { id: "confidence", label: "Confidence & self-worth" },
  { id: "parents", label: "Parents & caregivers" },
  { id: "experience", label: "The therapy experience" },
];

export type Testimonial = { id: number; who: string; age: number; topic: Topic; quote: string };

export const testimonials: Testimonial[] = [
  { id: 1, who: "Adult", age: 27, topic: "everyday", quote: "I came in feeling like I had to be the capable one in every room. I could get through work and handle everyone else’s problems, but the smallest inconvenience at home would leave me completely drained. Having space to slow down helped me notice how much I was carrying before I reached that point. I’m still figuring things out, but I don’t ignore the signs quite as quickly now." },
  { id: 2, who: "University student", age: 21, topic: "everyday", quote: "For a long time, I couldn’t explain what was wrong without saying “I’m just stressed.” I was sleeping irregularly, overthinking every conversation and then feeling guilty for not being productive. What helped was being able to unpack one thing at a time instead of having to explain my whole life in one sitting. It felt less overwhelming than I expected." },
  { id: 3, who: "Working professional", age: 32, topic: "everyday", quote: "I used to treat rest like something I had to earn after finishing everything. Of course, everything was never finished. Therapy helped me see that I was measuring my worth by how useful I could be to other people. I’m learning to pause without immediately calling it laziness, which sounds small but has been a real shift for me." },
  { id: 4, who: "Adult", age: 44, topic: "everyday", quote: "I had got so used to saying “it’s fine” that I was saying it even when it clearly wasn’t. I didn’t need someone to tell me how to live; I needed help hearing myself think. The conversations gave me room to be honest about feelings I’d been brushing aside for years. I left with more questions at first, but they were the right questions." },
  { id: 5, who: "Adult", age: 36, topic: "everyday", quote: "I expected therapy to be all about finding solutions. Instead, a lot of the value was in understanding why certain situations affected me so strongly. I started noticing my patterns rather than judging myself for having them. That little bit of distance has helped me respond more thoughtfully instead of reacting and regretting it later." },
  { id: 6, who: "Adult", age: 51, topic: "everyday", quote: "I am usually the person friends come to when they need to talk, so admitting that I needed support felt strange. I worried I would sound ungrateful because nothing in my life looked obviously wrong from the outside. It was a relief to talk about the things that were difficult without having to prove that they were difficult enough." },
  { id: 7, who: "University student", age: 19, topic: "students", quote: "I had built up this idea that everyone else knew exactly what they were doing and I was the only one making it up as I went along. I was comparing marks, internships, friendships and even how people spent their weekends. Talking through that pressure helped me see how unfairly I was judging myself. I’m still ambitious, just a little less cruel to myself about it." },
  { id: 8, who: "Young adult", age: 23, topic: "students", quote: "I reached out because I felt stuck between what my family expected and what I wanted for myself. Every option seemed to disappoint someone, and I kept postponing decisions until I felt completely certain. I’m learning that clarity doesn’t always arrive before a decision; sometimes it comes from being honest about what matters to me and taking the next step." },
  { id: 9, who: "Student", age: 20, topic: "students", quote: "My first instinct was to make jokes whenever a conversation got too close to something personal. I didn’t even realise how automatically I did it. Having a space where I could take my time and not perform being okay made it easier to talk properly. I appreciated not being pushed to share more than I was ready to." },
  { id: 10, who: "Early-career adult", age: 25, topic: "students", quote: "A setback at work made me question things that had nothing to do with that one situation. Suddenly I was convinced I wasn’t good at anything and had somehow fooled everyone. Working through the difference between one disappointing experience and my whole identity was genuinely useful. I still get self-doubt, but I don’t take every thought as a fact anymore." },
  { id: 11, who: "University student", age: 22, topic: "students", quote: "I was overwhelmed by the number of choices I thought I had to make immediately: career, relationships, where to live, what kind of person to become. I liked that I didn’t have to turn every session into a productivity exercise. Sometimes it was enough to understand why something mattered to me and what I was afraid of." },
  { id: 12, who: "Young adult", age: 24, topic: "students", quote: "I had been running on deadlines for so long that a quiet day made me anxious. I would invent something to worry about because slowing down felt unfamiliar. The process helped me notice that pattern without making me feel silly for it. I’m practising letting a day be a day, rather than treating every hour like a test I might fail." },
  { id: 13, who: "Adult", age: 29, topic: "relationships", quote: "I used to rehearse difficult conversations in my head for days, then avoid having them because I was afraid of upsetting someone. That usually meant I ended up resentful and the other person had no idea why. I have started saying things earlier and more clearly. It hasn’t made every conversation comfortable, but it has made them more honest." },
  { id: 14, who: "Adult", age: 34, topic: "relationships", quote: "I came in trying to understand why the same argument kept happening in different forms. I was focused on what the other person should change, and it took some reflection to recognise the parts I brought into the cycle too. That wasn’t always comfortable to look at, but it gave me something practical to work with instead of feeling completely powerless." },
  { id: 15, who: "Adult", age: 31, topic: "relationships", quote: "The word “boundaries” used to sound harsh to me, like I was being selfish or shutting people out. I’m beginning to understand that a boundary can be calm and respectful, and that saying yes when I mean no doesn’t actually help a relationship. I’m not perfect at it yet, but I feel less guilty for considering my own limits." },
  { id: 16, who: "Adult", age: 40, topic: "relationships", quote: "I was carrying a lot of frustration in my relationship and couldn’t work out how to talk about it without the conversation turning into a list of old grievances. Therapy gave me time to separate what I felt from what I wanted to communicate. I’ve become more aware of when I need a pause and when I’m ready to have the difficult conversation." },
  { id: 17, who: "Adult", age: 28, topic: "relationships", quote: "After a difficult breakup, I kept replaying every interaction looking for the exact moment things went wrong. I wanted a neat explanation that would make the sadness stop. What I found more helpful was making room for mixed feelings and accepting that not every question would have a satisfying answer. That helped me be gentler with myself while I adjusted." },
  { id: 18, who: "Adult", age: 37, topic: "relationships", quote: "I thought being a good partner meant anticipating what the other person needed before they asked. Over time, that turned into disappointment on both sides because I expected the same in return. Reflecting on this helped me see that care and mind-reading are not the same thing. I’m trying to ask more directly instead of assuming." },
  { id: 19, who: "Adult", age: 46, topic: "relationships", quote: "I had spent years keeping the peace in my family and calling it maturity. Eventually I realised I was agreeing to things that left me exhausted and then feeling angry in private. It helped to look at that pattern without blaming myself or everyone else. I’m learning that a respectful disagreement doesn’t automatically mean a relationship is in danger." },
  { id: 20, who: "Adult", age: 33, topic: "relationships", quote: "I found it hard to trust my own judgement after a relationship that left me second-guessing everything. I wanted reassurance for every decision, even small ones. Slowly, I’ve been practising noticing what I think and feel before asking everyone else what they think. It’s a work in progress, but I feel more connected to my own voice." },
  { id: 21, who: "Adult", age: 39, topic: "transitions", quote: "I was trying to meet everyone’s expectations while telling myself that my own needs could wait. A change in my family situation made that impossible to keep doing. Talking it through helped me recognise how often I confuse being responsible with doing everything alone. I’m getting better at asking for help before I reach breaking point." },
  { id: 22, who: "Adult", age: 47, topic: "transitions", quote: "When a major life change happened, I thought I should be handling it better because it was something other people had handled before me. I kept comparing my process to an imaginary timeline. It helped to hear myself say out loud that change can be difficult even when it is wanted. I’ve given myself more patience than I used to." },
  { id: 23, who: "Adult", age: 35, topic: "transitions", quote: "I came in feeling guilty about being frustrated with people I love. I thought the presence of frustration meant I was ungrateful. Making room for two feelings at once was surprisingly freeing: I can care deeply about my family and still need space. That distinction has made it easier to respond honestly rather than pretending everything is fine." },
  { id: 24, who: "Adult", age: 54, topic: "transitions", quote: "For most of my life I have been the one who sorts things out, keeps appointments and remembers what everyone needs. A period of change left me feeling unsettled in a way I didn’t know how to explain. I appreciated having somewhere to talk without needing to turn the conversation into a plan. Sometimes being heard was the first useful step." },
  { id: 25, who: "Adult", age: 42, topic: "transitions", quote: "I was navigating a transition that looked positive on paper, but emotionally it was much messier than I expected. I felt excited one day and lost the next, then judged myself for not being consistently happy. It was helpful to understand that mixed emotions can coexist. I stopped asking myself to feel one “correct” thing about the situation." },
  { id: 26, who: "Adult", age: 60, topic: "transitions", quote: "I had reached a stage where I was reassessing some decisions and wondering what I wanted the next few years to look like. I initially thought therapy was something you sought only when things were falling apart. Instead, the conversations helped me reflect on what I value and what I want to make more room for going forward." },
  { id: 27, who: "Working professional", age: 30, topic: "confidence", quote: "I tied a lot of my confidence to how well I was doing at work. When things went smoothly, I felt fine; one piece of criticism could ruin the rest of my week. I’ve been learning to hear feedback without turning it into a verdict on my entire character. That has made work feel less personal and my inner voice less exhausting." },
  { id: 28, who: "Adult", age: 27, topic: "confidence", quote: "I kept waiting until I felt confident before trying anything unfamiliar, which meant I avoided a lot of things I wanted to do. I thought confidence was something other people simply had. Reflecting on that helped me see how avoidance was keeping the fear alive. I’m trying smaller steps now rather than waiting for the fear to disappear first." },
  { id: 29, who: "Adult", age: 38, topic: "confidence", quote: "I had become very good at explaining why everyone else’s needs made sense and why mine could wait. When asked what I wanted, I often had no answer ready. The process of paying attention to my own preferences felt awkward at first, but it has become easier. I’m starting to make choices that reflect what matters to me, not only what is expected." },
  { id: 30, who: "Adult", age: 43, topic: "confidence", quote: "I came in feeling embarrassed that I was struggling with a decision I thought I should be able to make on my own. What helped was not being handed an answer. Instead, I was able to look at the different priorities and fears involved, and decide what felt consistent with my values. I left feeling clearer, even though the decision was still mine to make." },
  { id: 31, who: "Adult", age: 26, topic: "confidence", quote: "I had a habit of dismissing anything I did well and remembering every mistake in detail. A friend might tell me I had done a good job, and I would immediately list the things I could have done better. I’m practising giving my efforts a fairer assessment. It sounds basic, but noticing the pattern has changed how I talk to myself." },
  { id: 32, who: "Parent / caregiver", age: 38, topic: "parents", quote: "I first looked for guidance because ordinary disagreements at home were becoming bigger than I wanted them to be. I realised I was responding to the behaviour in front of me without always being curious about the feeling underneath it. I’m trying to slow down, listen first and set limits without escalating the moment. It has given me a different way to approach difficult evenings." },
  { id: 33, who: "Parent / caregiver", age: 42, topic: "parents", quote: "As a parent, I wanted a quick list of things to do differently. What stayed with me more was the reminder to notice my own reactions too. When I am already tired or worried, I can unintentionally make a small problem feel bigger. I’m learning to pause before responding and to repair things when I don’t get it right." },
  { id: 34, who: "Parent / caregiver", age: 35, topic: "parents", quote: "My child found it difficult to talk about feelings directly, and I was worried that asking questions would make them shut down even more. Thinking about different ways children express themselves helped me be more patient and observant. I’m trying not to demand an explanation on the spot. Sometimes connection starts with making the conversation feel less like an interrogation." },
  { id: 35, who: "Parent / caregiver", age: 46, topic: "parents", quote: "I was concerned about my child’s confidence at school and wasn’t sure how best to support them without adding more pressure. The discussions helped me reflect on the messages children can hear even when we mean well. I’ve been more mindful of praising effort, keeping conversations open and not making every difficult day into a problem to solve immediately." },
  { id: 36, who: "Caregiver", age: 33, topic: "parents", quote: "I felt guilty admitting that parenting could leave me overwhelmed. I love my child, so I thought I should always have the patience to handle every situation well. It was reassuring to acknowledge that care and exhaustion can exist together. I’m learning to notice when I need a break and to seek support instead of waiting until I feel depleted." },
  { id: 37, who: "Parent / caregiver", age: 40, topic: "parents", quote: "We were struggling to understand what would help our child feel more settled during a period of change. I appreciated being able to think about the situation from the child’s point of view rather than only looking at what was inconvenient for adults. It reminded me to make space for questions, routine and reassurance, even when there isn’t an instant fix." },
  { id: 38, who: "Parent / caregiver", age: 49, topic: "parents", quote: "I went in worried that asking for support meant I had somehow failed as a parent. I left with a more balanced view: children and families can need guidance at different points, and that does not have to be a judgement on anyone. The most useful part was having time to think carefully about our responses instead of reacting out of worry." },
  { id: 39, who: "Parent / caregiver", age: 37, topic: "parents", quote: "I used to label certain reactions as stubbornness because I didn’t know what else to call them. Learning to stay curious about what might be difficult for my child has helped me approach those moments with less frustration. I still need reminders, especially on busy days, but I am trying to understand before I correct." },
  { id: 40, who: "Parent of an adolescent", age: 44, topic: "parents", quote: "The teenage years brought conversations that seemed to end before they had really begun. I wanted to help, but my concern often came out sounding like criticism. Reflecting on that helped me notice the difference between trying to solve something and making it safe to talk about it. I’m working on listening a little longer before offering advice." },
  { id: 41, who: "Parent of a school-age child", age: 39, topic: "parents", quote: "I was worried that school difficulties were affecting my child’s confidence. I needed help separating the practical concerns from the fear I was carrying as a parent. Having space to think through both was valuable. It encouraged me to focus on what support might be useful rather than making each setback feel like a prediction of the future." },
  { id: 42, who: "Caregiver", age: 41, topic: "parents", quote: "I didn’t always understand why my child could manage one situation comfortably and find another very difficult. I was looking for a simple explanation, but it helped more to pay attention to patterns, context and the child’s experience. I feel better equipped to ask questions and work with the people supporting them, rather than jumping straight to conclusions." },
  { id: 43, who: "Parent / caregiver", age: 36, topic: "parents", quote: "I wanted to respond more calmly when my child became upset, but my instinct was to say “there’s nothing to worry about” and move on. I’ve realised that reassurance can sometimes sound like dismissal if I haven’t listened first. I am trying to acknowledge the feeling before helping them work through what happened." },
  { id: 44, who: "Adult", age: 31, topic: "experience", quote: "I was going through a difficult period and found it hard to talk about because I didn’t want to worry the people around me. Keeping everything private made me feel even more alone. Having a separate space to sort through my thoughts helped me put words to what I was experiencing. I didn’t leave with everything resolved, but I felt less tangled up in it." },
  { id: 45, who: "Adult", age: 48, topic: "experience", quote: "I assumed that because I could explain my situation logically, I should be able to move past it. Instead, I kept reacting emotionally in ways that surprised me. It helped to stop treating my feelings like an argument I needed to win. I’m learning that understanding something intellectually and processing it emotionally are not always the same thing." },
  { id: 46, who: "Adult", age: 24, topic: "experience", quote: "I was nervous before my first session because I imagined I would have to tell my whole story perfectly. It was a relief to discover that I could begin with whatever was on my mind that day. I didn’t have to organise everything in advance or know exactly what I needed. That made coming back feel much less intimidating." },
  { id: 47, who: "Adult", age: 34, topic: "experience", quote: "What I appreciated most was having time where I didn’t need to make my feelings sound reasonable or tidy. I often minimise things when I talk to friends because I don’t want to seem dramatic. Being able to explore the more complicated parts honestly helped me understand what I needed and what I wanted to handle differently." },
  { id: 48, who: "Adult", age: 56, topic: "experience", quote: "I came to therapy thinking that after a certain age, your habits and ways of thinking are simply fixed. I have found it useful to question some of those assumptions. Change has not been dramatic or overnight, but I notice myself pausing more often and considering another perspective. That feels meaningful at this point in my life." },
  { id: 49, who: "Adult", age: 29, topic: "experience", quote: "I had spent a long time trying to find the perfect explanation for why I felt unsettled. Every time I found one, another question appeared. The conversations helped me tolerate a little uncertainty and focus on what I could observe and change in the present. I still think deeply about things, but it doesn’t have to turn into an endless loop every time." },
  { id: 50, who: "Adult", age: 41, topic: "experience", quote: "I liked that the process did not feel like someone was grading how well I was coping. I could talk about progress one week and feel stuck the next without feeling that I had failed. That made it easier to be honest about what was actually happening. I’ve taken away a few ways of reflecting that I continue to use between difficult moments." },
];

/** A spread across ages and concerns for the home page. */
export const featuredIds = [46, 2, 32, 15, 6, 34, 10, 26];

export const privacyNote =
  "Shared anonymously. Names and identifying details are withheld to protect client confidentiality. Every person’s experience of therapy is their own.";
